### ISSUE TITLE
puma 5,   rails s error

### ISSUE THREAD

**Issue by huzhijia** [zombocom/puma_worker_killer#100]
05410000-105414000 r-- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/iso_8859_9.bundle
105414000-105418000 rw- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/iso_8859_9.bundle
105418000-10541c000 r-- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/iso_8859_9.bundle
10541c000-105420000 r-x /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/shift_jis.bundle
105420000-105424000 r-- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/shift_jis.bundle
105424000-105428000 rw- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/shift_jis.bundle
105428000-10542c000 r-- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/shift_jis.bundle
10542c000-105430000 r-x /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/gb18030.bundle
105430000-105434000 r-- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/gb18030.bundle
105434000-105438000 rw- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/gb18030.bundle
105438000-10543c000 r-- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/gb18030.bundle
10543c000-105440000 r-x /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/euc_jp.bundle
105440000-105444000 r-- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/euc_jp.bundle
105444000-105448000 rw- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/euc_jp.bundle
105448000-10544c000 r-- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/euc_jp.bundle
10544c000-105450000 r-x /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/euc_kr.bundle
105450000-105454000 r-- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/euc_kr.bundle
105454000-105458000 rw- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/euc_kr.bundle
105458000-10545c000 r-- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/euc_kr.bundle
10545c000-105460000 r-x /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/big5.bundle
105460000-105464000 r-- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/big5.bundle
105464000-105468000 rw- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/big5.bundle
105468000-10546c000 r-- /Users/xx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/arm64-darwin20/enc/big5.bundle
10546c000-105484000 r-x /Users/xx/.rvm/gems/ruby-2.7.2/gems/ffi-1.13.1/lib/ffi_c.bundle
105484000-105488000 r-- /Users/xx/.rvm/gems/ruby-2.7.2/gems/ffi-1.13.1/lib/ffi_c.bundle
105488000-10548c000 rw- /Users/xx/.rvm/gems/ruby-2.7.2/gems/ffi-1.13.1/lib/ffi_c.bundle
10548c000-1054a0000 r-- /Users/xx/.rvm/gems/ruby-2.7.2/gems/ffi-1.13.1/lib/ffi_c.bundle
1054a0000-1054a4000 rw-
146600000-146700000 rw-
146700000-146800000 rw-
146800000-147000000 rw-
147000000-147100000 rw-
147100000-147200000 rw-
147200000-147300000 rw-
147300000-147400000 rw-
147400000-147500000 rw-
147500000-147600000 rw-
147600000-147700000 rw-
147700000-147800000 rw-
147800000-148000000 rw-
148000000-148800000 rw-
148800000-149000000 rw-
149000000-149800000 rw-
149800000-14a000000 rw-
14a000000-14a800000 rw-
14a800000-14b000000 rw-
14b000000-14b800000 rw-
14b800000-14c000000 rw-
14c000000-14c800000 rw-
14c800000-14d000000 rw-
14d000000-14d800000 rw-
14d800000-14e000000 rw-
14e000000-14e800000 rw-
14e800000-14f000000 rw-
14f000000-14f800000 rw-
14f800000-150000000 rw-
150000000-150100000 rw-
150100000-150200000 rw-
150200000-150300000 rw-
150300000-150400000 rw-
150400000-150500000 rw-
150500000-150600000 rw-
150600000-150700000 rw-
150700000-150800000 rw-
150800000-151000000 rw-
151000000-151100000 rw-
151100000-151200000 rw-
151200000-151300000 rw-
151300000-151400000 rw-
151400000-151500000 rw-
151500000-151600000 rw-
151800000-152000000 rw-
156600000-156700000 rw-
156700000-156704000 rw-
156800000-157000000 rw-
157000000-157100000 rw-
157100000-157200000 rw-
157200000-157300000 rw-
157300000-157400000 rw-
157400000-157500000 rw-
157500000-157600000 rw-
157600000-157700000 rw-
157700000-157800000 rw-
157800000-158000000 rw-
158000000-158800000 rw-
158800000-159000000 rw-
159000000-159800000 rw-
159800000-15a000000 rw-
15a000000-15a800000 rw-
15a800000-15b000000 rw-
15b000000-15b800000 rw-
15b800000-15c000000 rw-
15c000000-15c800000 rw-
15c800000-15d000000 rw-
15d000000-15d800000 rw-
15d800000-15e000000 rw-
15e000000-15e800000 rw-
15e800000-15f000000 rw-
15f000000-15f800000 rw-
15f800000-160000000 rw-
160000000-162000000 rw-
162000000-162100000 rw-
16b5e4000-16ede8000 ---
16ede8000-16f5e4000 rw-
16f5e4000-16f5e8000 ---
16f5e8000-16f670000 rw-
180000000-190000000 r--
190000000-1a0000000 r--
1a0000000-1b0000000 r--
1b0000000-1c0000000 r--
1c0000000-1d0000000 r--
1d0000000-1e0000000 r--
1e0000000-1f0000000 r--
1f0000000-1fa000000 r--
1fa000000-1fc000000 rw-
1fc000000-1fe000000 rw-
1fe000000-200000000 r--
200000000-201238000 r--
201238000-206a60000 rw-
206a60000-208000000 r--
208000000-210000000 r--
210000000-220000000 r--
220000000-230000000 r--
230000000-240000000 r--
240000000-250000000 r--
250000000-260000000 r--
260000000-270000000 r--
270000000-280000000 r--
fc0000000-1000000000 ---
1000000000-7000000000 ---
[IMPORTANT]
Don't forget to include the Crash Report log file under
DiagnosticReports directory in bug reports.

**Comment by schneems** [comment]
I can't do anything with this. I don't think this is a PWK issue. Looks like a segfault. If you can reproduce the issue please open a new issue and provide a reproduction case https://www.codetriage.com/example_app
