### ISSUE TITLE
Please add support for rack >= 3

### ISSUE THREAD

**Issue by lucaskanashiro** [zombocom/puma_worker_killer#108]
rack 3 is out for a while and ideally puma_worker_killer should support it.

**Comment by schneems** [comment]
Rack in the gemspec is a development dependency https://github.com/zombocom/puma_worker_killer/blob/293fd38a883ad1ff0bbdc1f277c33ede90cff16a/puma_worker_killer.gemspec#L24, you can use this gem with Rack 3 in production today.
